name: Link Jira issue key in PR
on:
  pull_request:
    types: [opened]

jobs:
  link_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Find Jira Issue
        uses: cybervoid/gajira-get-issue@v1.1
        id: find
        with:
          input-text: ${{ github.head_ref }}

      - name: Update PR body
        uses: AsasInnab/pr-body-action@v1
        if: steps.find.outputs.issue != ''
        with:
          body: "[이슈 번호 : ${{ steps.find.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.find.outputs.issue }})<br><br>${{ github.event.pull_request.body }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
